package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Palettes (matching the brand specification)
val BrandPrimary = Color(0xFF00488D)
val BrandPrimaryContainer = Color(0xFF005FB8)
val BrandOnPrimaryContainer = Color(0xFFCADCFF)
val BrandBackground = Color(0xFFF7F9FC)
val BrandOnBackground = Color(0xFF191C1E)
val BrandSurface = Color(0xFFF7F9FC)
val BrandOnSurface = Color(0xFF191C1E)
val BrandOnSurfaceVariant = Color(0xFF424752)
val BrandSurfaceVariant = Color(0xFFE0E3E6)
val BrandSurfaceContainerLowest = Color(0xFFFFFFFF)
val BrandSurfaceContainerLow = Color(0xFFF2F4F7)
val BrandSurfaceContainer = Color(0xFFECEEF1)
val BrandSurfaceContainerHigh = Color(0xFFE6E8EB)
val BrandSurfaceContainerHighest = Color(0xFFE0E3E6)
val BrandOutlineVariant = Color(0xFFC2C6D4)
val BrandOutline = Color(0xFF727783)

// Status / Indicator colors
val StateOnlineGreen = Color(0xFF2E7D32)
val StateOfflineAmber = Color(0xFFB07100)
val StateFavoriteStar = Color(0xFFFFB400)
val StatePinkFixed = Color(0xFFFFD9E3)
val StateOnPinkFixed = Color(0xFF31111D)

// Dark Theme Palettes (matching Lumina Enterprise specification)
val DarkBrandPrimary = Color(0xFFB2D1FF)
val DarkBrandPrimaryContainer = Color(0xFF7FB6FF)
val DarkBrandOnPrimaryContainer = Color(0xFF004680)
val DarkBrandBackground = Color(0xFF0B1326)
val DarkBrandOnBackground = Color(0xFFDAE2FD)
val DarkBrandSurface = Color(0xFF0B1326)
val DarkBrandOnSurface = Color(0xFFDAE2FD)
val DarkBrandOnSurfaceVariant = Color(0xFFC2C6D2)
val DarkBrandSurfaceVariant = Color(0xFF2D3449)
val DarkBrandSurfaceContainerLowest = Color(0xFF060E20)
val DarkBrandSurfaceContainerLow = Color(0xFF131B2E)
val DarkBrandSurfaceContainer = Color(0xFF171F33)
val DarkBrandSurfaceContainerHigh = Color(0xFF222A3D)
val DarkBrandSurfaceContainerHighest = Color(0xFF2D3449)
val DarkBrandOutlineVariant = Color(0xFF424750)
val DarkBrandOutline = Color(0xFF8C919C)
